# Generated by Django 2.2.3 on 2019-08-28 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_bookinstance_borrower'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookinstance',
            options={'ordering': ['due_back'], 'permissions': (('can_read_private_section', 'Vip User'), ('User_watcher', 'User Watcher'), ('', ''))},
        ),
    ]
