# Generated by Django 2.2.3 on 2019-08-30 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_auto_20190828_0655'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookinstance',
            options={'ordering': ['due_back'], 'permissions': (('can_read_private_section', 'Vip User'), ('user_watcher', 'User Watcher'), ('librarian', 'Librarian'))},
        ),
    ]
